### ISSUE TITLE
Talks list task list

### ISSUE THREAD

**Issue by benjaoming** [djangocon/2019.djangocon.eu#170]
Need to have before publishing individual talks:

* [x] SOME previews
* [x] Keynotes go first
* [x] Keynote label for the keynotes
* [x] Everything else is ordered by speaker name
* [x] Detail pages generated by Django management command
* [x] Add a model to store employer support logo
* [ ] Detail page contains "Next talk" and "Previous talk" for easy navigation
